@startuml
    class Client{}

    interface Target{
        request()
    }

    class Adapter{
        request()
    }

    interface Adaptee{
        specificRequest()
    }

    Client --> Target

    Target <|-- Adapter
    Adaptee <|-- Adapter
@enduml