@startuml
abstract class Product{}

class ConcreteProduct{}

abstract class Creator{
    abstract factoryMethod()
    anOperation()
}

class ConcreteCreator{
    factoryMethod()
}

Product <|-- ConcreteProduct
Creator <|-- ConcreteCreator

ConcreteCreator --> ConcreteProduct
@enduml